---
- name: 1. Install Mysql server package
  apt: name=mysql-server state=present

- name: 2. Start Mysql Service
  shell: sudo mysql_install_db

- name: Install python Mysql package #required for mysql_db tasks
  apt: name=python-mysqldb state=present

- name: 3. Create a new database
  mysql_db: name=demo state=present collation=utf8_general_ci

- name: 4. Create a database user
  mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present

- name: 5a. Install MySQL extension for PHP
  apt: name=php5-mysql state=present

- name: 5b. Install Apache mod for MySql
  apt: name=php5-mysql state=present

- name: 6a. Install SqLite server package
  apt: name=sqlite3 state=present

- name: 6b. Install SqLite server package
  apt: name=libsqlite3-dev state=present

- name: 6c. Install SqLite extension for PHP
  apt: name=php5-sqlite state=present

- name: 7. Restart Apache
  service: name=apache2 state=restarted

